custofb = float(input("custo de fábrica:  "))
percentD = int(input("percentual  do distribuidor: "))
percentI = int(input("percentual de imposto: "))
custoF = custofb + (custofb * (percentD/100)) + (custofb * (percentI/100))
print("\n")
print("Custo de fábrica = R$ ",custofb)
print("Percentual do distribuidor = ",percentD,"%")
print("Percentual dos Impostos    = ",percentI,"%")
print("Custo Final = R$ %.2f "%custoF)
